#!/bin/bash
VERSION=0.1

# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
dir_scripts="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

Usage(){
	echo ""
	echo "Usage:"
	echo "miRNA-Tools [command]"
	echo ""
	echo "Available commands:"
	echo "    init	initialize current directory"
	echo "    version	show tool version"
	echo ""
}

if [ "$1" == "version" ]
then
	echo "miRNA-Tools v$VERSION"
elif [ "$1" = "init" ]
then
	# See Gordon Davisson comment: http://stackoverflow.com/questions/9057387/process-all-arguments-but-first
	$dir_scripts/Utility/init $dir_scripts ${@:2}
else
	Usage
fi
