# Utilitary functions
drawLines <- function() {
	lines(x=c(-50,-50), y=c(0,17), lty="solid", col="black")
	lines(x=c(-40,-40), y=c(0,9.5), lty="solid", col="black")
	lines(x=c(-40,-40), y=c(10,17), lty="solid", col="black")
}

drawText <- function(id) {
	mainText <- pase("Classification of the small RNA species - ", id, sep="")
	text(x=20, y=19, mainText, cex=1.3)
	title(xlab="Reads mapped (%)")
	text(x = -45, y=13.3, 'Genomic Repeats', srt=90, cex=1.1)
	text(x = -45, y=5, 'Functional ncRNAs', srt=90, cex=1.1)
	text(x = -55, y=8, 'RNA species', srt=90, cex=1.1)
}

drawPlot <- function(data, filetype, outputBasename) {
	if (type == "jpeg") {
		filename = paste("classification_", outputBasename, ".jpeg", sep="")
		jpeg(filename)
	}
	if (type == "tiff") {
		filename = paste("classification_", outputBasename, ".tiff", sep="")
		tiff(filename)
	}
	par(mai=c(1.5,4,1,1), xpd=NA)
	options(scipen = 50, digits = 10)
	barplot(a[,1], names=row.names(a), horiz=TRUE, las=2, xlim=c(0,100))
	drawText(outputBasename)
	drawLines()
	dev.off()
}

# Main
argv <- commandArgs(trailingOnly = T)

if (length(argv) == 2) {
	filename <- argv[1]
	data <- read.table(filename, row.names=1)
	outputBasename <- argv[2]
	type <- argv[3]

	drawPlot(data, type, outputBasename)
} else {
	cat("\nUsage:\n")
	cat("PlotClassificator.R <filename> <output>\n")
	cat("filename: name of the file generated by LengthDistributionAnalysis.sh\n")
	cat("output: suffix for the output filename and plot title.\n")
	cat("        output filename is: classification_<output>.jpeg/.tiff\n")
	cat("        title is: Classification of the small RNA species - <output>\n\n")
	cat("        type: type of file (jpeg, tiff, pdf, etc...)\n")
}
