argv <- commandArgs(trailingOnly = T)

if (length(argv) == 3) {
    inputFilename <- argv[1]
    reference <- argv[2]
    output <- argv[3]
    
    # 1. Open device
    outputFilename <- paste("lengthDist_", output, "_relative.jpeg", sep="")
    jpeg(outputFilename)

    # 2. Read data
    dist <- read.table(inputFilename)
    total <- read.table(reference)

    # 3. Plot the data
    maxRange <- max(dist[2], total[2]) + (5 - (max(dist[2], total[2]) %% 5))

    names(dist)[1] <- "RNA length (nt)"
    names(dist)[2] <- "Reads abundance (%)"
    plot(dist, type="l", xlim=range(10,40), ylim=range(0,maxRange), xaxt="n", yaxs="i", col="red")
    lines(total, type="l", col="black")

    # 4. Annotate the plot
    legend(28, 21, c("Total Sequences", output), lty=c(1,1), col=c("black", "red"))
    titleName <- paste("Relative Contribution - ", output, sep="")
    title(main=titleName)
    axis(1, at=10:40, labels=10:40)

    dev.off()

} else {

    cat("\nUsage:\n")
    cat("PlotRelativeLengthDistribution.R <filename> <reference> <output>\n")
    cat("filename: name of the file generated by LengthDistributionAnalysis.sh\n")
    cat("reference: Length distribution file to compare our results with.\n")
    cat("output: suffix for the output filename and plot title.\n")
    cat("        output filename is: lengthDist_<output>.txt\n")
    cat("        title is: Length Distribution Analysis - <output>\n\n")

}
