argv <- commandArgs(trailingOnly = T)

if (length(argv) == 2) {
    inputFilename <- argv[1]
    output <- argv[2]
    
    # 1. Open device
    outputFilename <- paste(output, ".tiff", sep="")
    message <- paste("\t\tSaving plot to: ", outputFilename, "\n", sep="")
    cat(message)
    tiff(outputFilename)

    # 2. Read data
    dist <- read.table(inputFilename)

    # 3. Plot the data
    maxRange <- max(dist[2]) + (5 - (max(dist[2]) %% 5))

    names(dist)[1] <- "RNA length (nt)"
    names(dist)[2] <- "Reads abundance (%)"
    plot(dist, type="l", xlim=range(10,40), ylim=range(0,maxRange), xaxt="n", yaxs="i")

    titleName <- paste("Length Distribution Analysis - ", basename(output), sep="")
    title(main=titleName)
    axis(1, at=10:40, labels=10:40)
    dev.off()
} else {
    cat("\nUsage:\n")
    cat("PlotLengthDistribution.R <filename> <output>\n")
    cat("filename: name of the file generated by LengthDistributionAnalysis.sh\n")
    cat("output: suffix for the output filename and plot title.\n")
    cat("        output filename is: lengthDist_<output>.txt\n")
    cat("        title is: Length Distribution Analysis - <output>\n\n")
}
